import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Kitchen Sink App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h1>Next.js Kitchen Sink App</h1>
        {children}
      </body>
    </html>
  );
}
